### ISSUE TITLE
scanForPeripherals 调用时报错

### ISSUE THREAD

**Issue by lynzz** [lynzz/BluetoothPrinter#2]
![image](https://user-images.githubusercontent.com/348917/27794031-0ab871a4-6033-11e7-8f83-23634578ead3.png)

打印设备：Xprinter XP-N160II

**Comment by lynzz** [comment]
1. keep 没传也会报  [Elog] 参数类型错误，但现设备是可以获取的到
2. keep 没传时，会一直扫描设备（不知是否正常）
3. 执行 connectPeripheral 后，没反应，还是一直在扫描设备

**Comment by mk2016** [comment]
1.不传参数时，参数会变成[null], 添加了NSNull 类型判断。
2.keep没传时，也会一直扫描，只是不会持续回调JS方法
3.应该是 没链接上，已做了调整
